### ISSUE TITLE
KeyError: 'familyList'

### ISSUE THREAD

**Issue by Remendado** [NickWaterton/eWeLink-mqtt#11]
suddenly after more than a year of stable work
-------------------------------------------------------------------------------------
{'error': 407, 'msg': 'the path of request is not allowed with appid:4s1FXKC9FaGfoqXhmXSJneb3qcm1gOak', 'data': {}}

[2024-03-29 10:09:15,328][ERROR](Main.EwelinkClient  ) 'familyList'
Traceback (most recent call last):
  File "/root/eWeLink-mqtt/./ewelink.py", line 297, in start_connection
    homes = await self.get_homes()
  File "/root/eWeLink-mqtt/custom_components/sonoff/core/ewelink/cloud.py", line 180, in get_homes
    return {i["id"]: i["name"] for i in resp["data"]["familyList"]}
KeyError: 'familyList'

**Comment by NickWaterton** [comment]
The appID secrets expire after one year, and have to be renewed.

Are you running the latest version? The appID’s were updated a while back.

I may have to upload the latest version though.

**Comment by Remendado** [comment]
with clear install of latest version i see this:

Installed custom_components
Traceback (most recent call last):
  File "/root/eWeLink-mqtt/./ewelink.py", line 189, in <module>
    from custom_components.sonoff.core.ewelink.__init__ import XRegistry, SIGNAL_ADD_ENTITIES
  File "/root/eWeLink-mqtt/custom_components/sonoff/__init__.py", line 29, in <module>
    from .core import devices as core_devices
  File "/root/eWeLink-mqtt/custom_components/sonoff/core/devices.py", line 22, in <module>
    from ..climate import XClimateNS, XClimateTH, XThermostat
  File "/root/eWeLink-mqtt/custom_components/sonoff/climate.py", line 6, in <module>
    from homeassistant.const import UnitOfTemperature, MAJOR_VERSION, MINOR_VERSION
ImportError: cannot import name 'UnitOfTemperature' from 'homeassistant.const' (/root/eWeLink-mqtt/homeassistant/const.py)
