### ISSUE TITLE
Cannot start (custom_components?)

### ISSUE THREAD

**Issue by borazslo** [NickWaterton/eWeLink-mqtt#8]
I've made a fresh clone of the repo than I've started the ewelink.py, but I'received the following error message:
Traceback (most recent call last):
  File "ewelink.py", line 189, in <module>
    from custom_components.sonoff.core.ewelink.__init__ import XRegistry, SIGNAL_ADD_ENTITIES
  File "[...]/eWeLink-mqtt/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "[...]/eWeLink-mqtt/custom_components/sonoff/core/devices.py", line 20, in <module>
    from .ewelink import XDevice
  File "[...]/eWeLink-mqtt/custom_components/sonoff/core/ewelink/__init__.py", line 7, in <module>
    from .base import SIGNAL_CONNECTED, SIGNAL_UPDATE, XDevice, XRegistryBase
  File "[...]/eWeLink-mqtt/custom_components/sonoff/core/ewelink/base.py", line 35, in <module>
    class XRegistryBase:
  File "[...]/eWeLink-mqtt/custom_components/sonoff/core/ewelink/base.py", line 36, in XRegistryBase
    dispatcher: dict[str, list[Callable]] = None
TypeError: 'type' object is not subscriptable

Python 3.8.2, OSX

Please, help me!

**Comment by borazslo** [comment]
Updateing to Python 3.10 has solved my problem.
